spring:
  application:
    name: running

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3395/running
    username: local
    password: local


logging:
  level:
    org.springframework:
      web: DEBUG


token:
  expiration:
    access: 14400
    refresh: 144000

oauth:
  google:
    token_url: "https://oauth2.googleapis.com/token"
