server:
  name: running-backend
  type: blue

spring:
  application:
    name: running
  config:
    import: optional:file:.env[.properties]

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_HOST}:3306/running
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    properties:
      hibernate:
        show_sql: true

logging:
  level:
    org.springframework:
      web: DEBUG
      security: DEBUG


token:
  expiration:
    access: 14400
    refresh: 144000

credentials:
  file-path:
    google: "credentials/GoogleCredential.json"
    apple: "credentials/AppleCredential.json"

oauth:
  google:
    token_url: "https://oauth2.googleapis.com/token"
  apple:
    token_url: "https://appleid.apple.com/auth/token"

springdoc:
  version: '@project.version@'
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
    doc-expansion: none
  paths-to-match:
    - /api/**
