spring:
  application:
    name: running

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3395/running
    username: local
    password: local

  jpa:
    properties:
      hibernate:
        show_sql: true

logging:
  level:
    org.springframework:
      web: DEBUG
      security: DEBUG


token:
  expiration:
    access: 14400
    refresh: 144000

credentials:
  file-path:
    google: "src/main/resources/credentials/GoogleCredential.json"

oauth:
  google:
    token_url: "https://oauth2.googleapis.com/token"
    grant_type: "authorization_code"
    redirect_url: "http://localhost:8080/api/v1/oauth/google"
